# Generated by Django 4.2.3 on 2023-08-01 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('department', models.CharField(max_length=100, verbose_name='department')),
                ('level', models.CharField(max_length=100, verbose_name='level')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip code ')),
                ('phone', models.CharField(max_length=300, verbose_name='Contact Phone ')),
                ('email_address', models.EmailField(max_length=300, verbose_name='Email')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.CharField(max_length=100, verbose_name='Quiz_number')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('quiz', models.CharField(max_length=100, verbose_name='quiz')),
                ('description', models.TextField(blank=True)),
                ('registeredStudents', models.ManyToManyField(blank=True, to='assignment.studentusers')),
            ],
        ),
    ]
